name: pausable_timer
description: A timer implementation that can be paused, resumed and reset.
homepage: https://github.com/mateusfccp/pausable_timer
repository: https://github.com/mateusfccp/pausable_timer
funding:
  - https://github.com/sponsors/mateusfccp

version: 3.1.0+3

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  clock: ^1.1.0

dev_dependencies:
  fake_async: ^1.3.1
  lints: ^3.0.0
  test: ">=1.24.0"
